### ISSUE TITLE
Split example_testing.ipynb into two examples

### ISSUE THREAD

**Issue by apetros** [realgjl/sfcNordic#5]
The example_testing.ipynb runs the SFC with multiple kp ki values.

Please prepare another example file that simply initialises the variables and runs the SFC function with one specific set of parameters. Without tuning.

It should then be:

example_testing.ipynb
example_tuning.ipynb

**Comment by albertjlguo** [comment]
Updated~

**Comment by apetros** [comment]
Seems great!
